### ISSUE TITLE
An error occoured during execution

### ISSUE THREAD

**Issue by ircmage** [Avenze/rpf2fivem-repository#17]
i have this error when trying to convert texture on this addons
https://www.gta5-mods.com/vehicles/audi-rs-6-c8-beta-version/download/119167

[latest.log](https://github.com/Avenze/rpf2fivem-repository/files/7046155/latest.log)

**Comment by Avenze** [comment]
yeah, this has to do with the invalid slice pitch, I need to do more investigation into this issue.

**Comment by Avenze** [comment]
refer to https://github.com/Avenze/rpf2fivem-repository/issues/20
