### ISSUE TITLE
unpacked stream files end up corrupt

### ISSUE THREAD

**Issue by memecian** [Avenze/rpf2fivem-repository#21]
steps to reproduce:

1. Add any car mod [gta5-mods](https://www.gta5-mods.com/) to queue
2. Start conversion
3. Compare yft/ytd in extracted folder with those in the mod's dlc.rpf

will add further info @ ~19:00 UTC

**Comment by marinofranz** [comment]
can confirm, i have same issue

**Comment by Avenze** [comment]
I'd like to get back into working on it, however, I'm having issues with the unpacking process, I'll push all my changes to the development branch, and I'd be grateful if anyone with a better eye can see what I'm doing wrong :)

**Comment by Avenze** [comment]
fixed as of https://github.com/Avenze/rpf2fivem-repository/issues/23
