### ISSUE TITLE
 Program closes when selecting folder with externally hosted mods from GTA5 Mods website

### ISSUE THREAD

**Issue by Jay3486** [Avenze/rpf2fivem-repository#26]
Hello! I've been using your program successfully to install mods from the GTA5 Mods website. However, I'm experiencing an issue where the program unexpectedly closes when I try to select a folder containing mods that are externally hosted (but still from the GTA5 Mods website). This issue occurs with various file formats (zip, rar, 7z).

**Comment by Avenze** [comment]
hi there! I apologize for this, however folder conversion isn't working yet, as I'm still working on it after I rewrote it to support texture compression.

**Comment by Avenze** [comment]
folder conversion has been implemented and should work properly
