### ISSUE TITLE
Program crashes whenever it starts uncompressing a file.

### ISSUE THREAD

**Issue by xGenius123** [Avenze/rpf2fivem-repository#27]
As the title says, when I start the download process the program crashes as soon as it finds the archive and begins the decompressing process. The vehicle I was testing it on is the 2015 Cadillac Escalade thats featured in the tutorial. I also attached the latest log file.
[latest.log](https://github.com/Avenze/rpf2fivem-repository/files/12240157/latest.log)

**Comment by Avenze** [comment]
what build of the tool are you on? try using combined-support@3.1.0-patch1, https://github.com/Avenze/rpf2fivem-repository/releases/tag/combined-support%403.1.0-patch1, and reach out if it still doesn't work.

**Comment by xGenius123** [comment]
I used 3.0.0 and 3.1.0. Both with the same results.
I even downgraded to the version from August 2021. The files did convert, but it seemed like in the process ytd's had gone missing.

**Comment by kj4lxc** [comment]
Can confirm the issue in both 3.0.0 and 3.1.0.  Did try using each format supported .7z, .rar, and .zip.  Was using this URL to do my testing. https://files.gta5-mods.com/uploads/brute-mr-tasty-gta-iv-style-add-on-liveries-template-sound-custom-shards/8e29c4-mrtasty.rar  I repacked into the other formats for my testing.  It just hits uncompressing then hangs, then dies.  No error in log just, *program closes*

**Comment by Avenze** [comment]
thank you for reporting, I'm gonna do some debugging and see what might be causing this!

**Comment by Avenze** [comment]
can very well confirm, this issue is affecting me aswell, and I might have figured out the issue, do you mind downloading this build and just let me know if it works for you aswell?

https://cdn.thefrostcloud.com/resources/frostcloud/rpf2fivem/combined-support_3.1.0-patch2.rar

**Comment by xGenius123** [comment]
Sorry for the late response but had a lot of thing on my head and kinda forgot about this. From a few test i did it looks like this version works well

**Comment by Avenze** [comment]
alrighty! I'll then push that to production and create a new release so people who are experiencing the same issues shall have them solved!

thanks for helping out!

**Comment by Scones91** [comment]
This issues seems to be happening in patch 2 aswell
