### ISSUE TITLE
Redo folder structure to use fxmanifest.lua layout instead of __resource.lua

### ISSUE THREAD

**Issue by Avenze** [Avenze/rpf2fivem-repository#9]
https://github.com/vscorpio/gta5rpf-to-fivem/issues/15

**Comment by userMacieG** [comment]
https://github.com/Avenze/rpf2fivem-repository/pull/12
https://github.com/Avenze/rpf2fivem-repository/pull/13

**Comment by Avenze** [comment]
@userMacieG great! thank you alot! I'll test it and I'll create a release for it!

**Comment by Avenze** [comment]
done.
